# Generated by Django 2.0.7 on 2019-02-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogtopic_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
